### ISSUE TITLE
No check for creative mode on server packet handling

### ISSUE THREAD

**Issue by ItsThosea** [sorae42/easyfind#1]
https://github.com/sorae42/easyfind/blob/84ec4c031cf5f4fb0402154aa79c9a8f26c73fd8/src/main/java/net/fortytoo/easyfind/easyfind/EasyFind.java#L13-L15

There's no check on the server for if the player is in creative mode, so a malicious client can simply send the packet in any gamemode to obtain an item. 
Since there is no check in the Spotlight screen you can also use this by having your gamemode changed while having the menu open.
On the server, you should check w/ `player.interactManager.isCreative()` which is what the normal creative screen packets do.
In Spotlight, you should override tick and check if the player is still in creative and close otherwise.

**Comment by sorae42** [comment]
Is there anyway I can test this out?

**Comment by ItsThosea** [comment]
Start a server with the mod, make sure you have no op or permissions, make a slightly modified version for your client that adds like, a clientside command or something for activation, and make that command send the packet with a stack of diamonds or something.

**Comment by ItsThosea** [comment]
For the spotlight not closing thing just make a command block that sets your gamemode to survival with a long repeater chain to delay it and then just keep spotlight open.

**Comment by sorae42** [comment]
It's seem the mod doesn't load on the server cuz I believe I don't have implementation for that. I also can't give myself an item on dedicated server thru easyfind.

**Comment by sorae42** [comment]
> It's seem the mod doesn't load on the server cuz I believe I don't have implementation for that. I also can't give myself an item on dedicated server thru easyfind (noticed just now).

My mod is entirely client-sided so implementing server-mod-init would be redundant here. But I do have to fix the latter.

**Comment by sorae42** [comment]
Should be good to go.
