### ISSUE TITLE
Backporting plans

### ISSUE THREAD

**Issue by sorae42** [sorae42/easyfind#2]
I might plan on backporting the mod to previous patch version of Minecraft if there are enough demands (and I have the time to do so).

Forge port is not possible. I will have to remake this mod for forge eco-system (since there are some build projects still stuck at 1.12.2), if there are demands and I have the time and mean to do so.

**Comment by sorae42** [comment]
Backported to 1.19.2.

**Comment by Shywizz** [comment]
1.20.1 ?

**Comment by sorae42** [comment]
> 1.20.1 ?

Sure, I will look into it.

**Comment by sorae42** [comment]
> 1.20.1 ?

Could you try updating your version to 1.20.2? 1.20.1 has so much problem that I am unable to fix.

**Comment by sorae42** [comment]
> 1.20.1 ?

I am unable to port back to 1.20.1 due to technical issues so 1.20.2 is the least version I could backport to.

**Comment by sorae42** [comment]
I won’t be doing any backporting anymore as there are like 2-3 versions to maintain at the moment.

Feel free to fork and do backport yourself if you want to.

**Comment by sorae42** [comment]
More people are requesting for 1.20.1 port so I might need to do it now.

**Comment by sorae42** [comment]
It's impossible anymore! EasyFind has been ported to 1.20.1 now! 🎉
